name: Release

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24

      - name: Release
        run: |
          npx \
            -p semantic-release \
            -p @semantic-release/commit-analyzer \
            -p @semantic-release/release-notes-generator \
            -p @semantic-release/changelog \
            -p @semantic-release/git \
            semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update floating tag
        run: |
          git fetch --tags
          EXACT=$(git tag --sort=-v:refname | head -n1)
          FLOATING=$(echo $EXACT | cut -d. -f1)
          git tag --force $FLOATING $EXACT 
          git push --force origin $FLOATING
